import 'package:flutter/material.dart';

const Color menthePrimaryColor = Color(0xFF4CA6A8);
const Color mentheSecondaryColor = Color(0xFF357B7C);
const Color mentheLightColor = Color(0xFFBBECED);
const Color blueDarkPrimaryColor = Color(0xFF071232);
const Color blackColor = Color(0xFF000000);
const Color whiteColor = Color(0xFFFFFFFF);
const Color greyPrimaryColor = Color(0xFF4B5060);
const Color greySecondaryColor = Color(0xFFBCBCBC);
const Color greyTertiaryColor = Color(0xFF616471);
const Color greyQuaternaryColor = Color(0xFFFBFBFB);
const Color greyQuinaryColor = Color(0xFFF3F3F3);
const Color greySixanaryColor = Color(0xFFF7F7F7);
const Color yellowDarkColor = Color(0xFFFFC300);
const Color mauvePrimaryColor = Color(0xFF816CFF);
const Color greenPrimaryColor = Color(0xFF00D259);
const Color redPrimaryColor = Color(0xFFFF0000);
const Color grayscale400 = Color(0xFF97A3B6);
const Color grayscale50 = Color(0xFFF9F9FA);