// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1ZoZ_HO2E0vZISbCy-hTcscwWgewgjbU',
    appId: '1:1020937272589:web:45c72344c15a8791ae0444',
    messagingSenderId: '1020937272589',
    projectId: 'my-cardoil-project',
    authDomain: 'my-cardoil-project.firebaseapp.com',
    storageBucket: 'my-cardoil-project.appspot.com',
    measurementId: 'G-YJZ96L2THG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNQd-qNIrOQHVGHI9T4mQIRR3Eoi70AC8',
    appId: '1:1020937272589:android:3af7034cb5ba7f00ae0444',
    messagingSenderId: '1020937272589',
    projectId: 'my-cardoil-project',
    storageBucket: 'my-cardoil-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZSawTLlNQHnmn3t3NiWmg_DYRNFyaZzA',
    appId: '1:1020937272589:ios:1ab1697609df5606ae0444',
    messagingSenderId: '1020937272589',
    projectId: 'my-cardoil-project',
    storageBucket: 'my-cardoil-project.appspot.com',
    iosClientId: '1020937272589-b3u4hmc9sp3qo21p752vfolfu8mp5150.apps.googleusercontent.com',
    iosBundleId: 'com.example.cardOil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZSawTLlNQHnmn3t3NiWmg_DYRNFyaZzA',
    appId: '1:1020937272589:ios:1ab1697609df5606ae0444',
    messagingSenderId: '1020937272589',
    projectId: 'my-cardoil-project',
    storageBucket: 'my-cardoil-project.appspot.com',
    iosClientId: '1020937272589-b3u4hmc9sp3qo21p752vfolfu8mp5150.apps.googleusercontent.com',
    iosBundleId: 'com.example.cardOil',
  );
}
